/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:12e6aab0-e1ef-4117-83ef-6f7c92cf5a7f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Z5fhMGEr4",
    "aws_user_pools_web_client_id": "6sg7jgelhekfkt6hi867gftgn2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "uploadbucketa29f2-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
